sudo: required
sevices:
    - docker
before_install:
    - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in newworld-262922-086c0d55c236.json.enc -out ./newworld-262922-086c0d55c236.json -d
    - curl https://sdk.cloud.google.com | bash > /dev/null;
    - source $HOME/google-cloud-sdk/path.bash.inc
    - gcloud components update kubectl
    - gcloud auth activate-service-account --key-file service-account.json